### PR TITLE
Create: disguising_your_scraper.md

### PR DESCRIPTION
**Pull request by justfoolingaround**

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Ayy, KR!

**Comment by justfoolingaround** [comment]
<p align="center">Aye Arjix! <code>  </code> </p>

**Comment by Blatzar** [comment]
The info is neatly formatted and very good. Perfect for this repo, but **Response handling algorithms** is too unexplained. Please explain either the code or concept in a way a newbie can understand. Most newbies don't understand sessions, let alone how to use them.

**Comment by justfoolingaround** [comment]
Aight, explained it all!

**Comment by Blatzar** [comment]
Thank you :heart:

**Pull request merged**
